### ISSUE TITLE
Issue with the extension running in devcontainer

### ISSUE THREAD

**Issue by AT-Education** [excalidraw/excalidraw-vscode#142]
### Steps to reproduce:
- create a github codespace
- add devcontainer config file with extension such as: `"customizations": {
		"vscode": {
			"extensions": [	"pomdtr.excalidraw-editor"]
		}
	}`
- trying to open a excalidraw file: nothing happens
- checking extensionhost output, getting following error: 
![Screenshot from 2024-06-15 13-18-33](https://github.com/excalidraw/excalidraw-vscode/assets/11267308/63a872f9-af99-4fa4-960d-729da309cf1f)

**Comment by game7** [comment]
Having similar issue.  In my case I'm using devcontainer locally (no codespaces) and the extension has worked fine in the past, however if/when I open the project "in a unique volume" the plugin appears greyed out in the extension pane and excalidraw files are not recognized when opened

**Comment by XF-FW** [comment]
Same here.

```
2024-08-30 11:21:22.703 [info] Extension host started
2024-08-30 11:21:27.766 [info] ExtensionService#_doActivateExtension pomdtr.excalidraw-editor, startup: false, activationEvent: 'onCustomEditor:editor.excalidraw'
2024-08-30 11:21:27.837 [error] Activating extension pomdtr.excalidraw-editor failed due to an error:
2024-08-30 11:21:27.837 [error] Error: 
	at I.xb (https://assets.github.dev/stable/fee1edb8d6d72afddff41e5f71a671c73ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:111:56325)
	at async Promise.all (index 0)
	at async s.n (https://assets.github.dev/stable/fee1edb8d6d72afddff41e5f71a671c73ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:6410)
	at async s.m (https://assets.github.dev/stable/fee1edb8d6d72afddff41e5f71a671c73ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:6373)
	at async s.l (https://assets.github.dev/stable/fee1edb8d6d72afddff41e5f71a671c73ed924b9/out/vs/workbench/api/worker/extensionHostWorker.js:96:5830)
2024-08-30 11:21:30.923 [info] Eager extensions activated
```

**Comment by schaumtier** [comment]
same here

**Comment by matt-deboer** [comment]
As a workaround, you can add the following to your `devcontainer.json` to force excalidraw to run in the host window...(though I'm not sure this will solve the problem for codespaces)
```
 ...
"customizations": {
   "vscode": {
      "settings": {
	...
	"remote.extensionKind": {
	   "pomdtr.excalidraw-editor": [
	      "ui"
	   ]
	}
      },
      "extensions": [
	   ...
	   "pomdtr.excalidraw-editor"
      ]
   }
}
...
```

**Comment by mamiba** [comment]
Thanks @matt-deboer! Your workaround works in my GitHub codespace.
(naturally, I'd prefer it if it were no longer necessary)
